name = "Central Siberian Yupik"
version = "0.1.1"

[macos]
system_pkg_id = "no.divvun.MacDivvun.ess"

[windows]
system_product_code = "74533FD5-3162-4687-AA5D-63DF9043E25C"
msoffice_product_code = "4228C71A-8335-4781-A4AE-179FCF063473"
