template = "https://github.com/giellalt/template-lang-und"
rev_id = 333
template_sha = "a03015fd00a15a0ad51da907dc4891c29ab9c8b2"

[replacements]
__GLOTTOLOG_ID__ = "cent2128"
__REPO__ = "lang-ess"
__UND2C__ = "ess"
__UNDEFINED__ = "Central Siberian Yupik"
__UND__ = "ess"
