template = "https://github.com/giellalt/template-lang-und"
rev_id = 311
template_sha = "c4d2b17b988e0fed439969cd55ec0e02eb7d2e4b"

[replacements]
__GLOTTOLOG_ID__ = "cent2128"
__REPO__ = "lang-ess"
__UND2C__ = "ess"
__UNDEFINED__ = "Central Siberian Yupik"
__UND__ = "ess"
