template = "https://github.com/giellalt/template-lang-und"
rev_id = 330
template_sha = "ca06c138bb7dc0942a15e60b710a001352e6ebde"

[replacements]
__GLOTTOLOG_ID__ = "cent2128"
__REPO__ = "lang-ess"
__UND2C__ = "ess"
__UNDEFINED__ = "Central Siberian Yupik"
__UND__ = "ess"
