[package]
name = "ess"
human_name = "Central Siberian Yupik"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.ess]
filename = "ess-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-ess"
platform = "windows"
uuid = "74533FD5-3162-4687-AA5D-63DF9043E25C"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.ess"
package = "speller-ess"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-ess-mso"
platform = "windows"
uuid = "4228C71A-8335-4781-A4AE-179FCF063473"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-ess"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
